services:
  - type: web
    name: almoxarifado
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python init_render_db.py && gunicorn src.main:app --bind 0.0.0.0:$PORT
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true